data:
  raw_csv: "data/01_raw/data.csv"

split:
  test_size: 0.3
  random_state: 17
  stratify: true

model:
  kind: random_forest
  n_estimators: 200
  max_depth: null
  random_state: 17
  n_jobs: -1

autogluon:
  time_limit: 60
  presets: "medium_quality"
  problem_type: "binary"
  label: "income_encoded"
  eval_metric: "average_precision"
  model_path: "data/06_models/ag_production"
  seed: ${seed}

seed: 21

wandb:
  enabled: True
  project: "asi-group-15-01"

artifacts:
  cleaned_data:
    name: "clean_data"
    type: "dataset"
    path: "data/02_interim/clean.parquet"
  ag_model:
    name: "ag_model"
    type: "model"
    path: ${autogluon.model_path}
    aliases:
      - "latest"
      - "candidate"
